remote_theme: page-themes/time-machine2v0.2.0
plugins:
- jekyll-remote-theme
title: Putta Shrisha
description: my name is Sirisha. I have recently completed my Bachelor’s degree in Computer Science Engineering from JNTU University. I come from Tirupati- Andhra pradesh
